#!/bin/bash
#PBS -j oe
#PBS -q huge
#PBS -l select=1:ncpus=1:hpcluster=True
#PBS -N mol_INDEX
#PBS -o mol_INDEX.log

# Capture the start time
START_TIME=$(date +%s)

echo "Starting job at:" $(date)
cd $PBS_O_WORKDIR

module load amber/amber22
source /SFS/project/kw/kimbry/venvs/sfl-env3/bin/activate

bash 00_reset.sh mol_INDEX
python rdkit_chg.py
rm -rf pdb
mkdir pdb
mv ligand.pdb ligand_fixed.mol pdb
bash run.sh

# Capture the end time
END_TIME=$(date +%s)

# Compute total runtime
TOTAL_TIME=$((END_TIME - START_TIME))

# Calculate days, hours, minutes, and seconds
DAYS=$((TOTAL_TIME / 86400))
HOURS=$(( (TOTAL_TIME % 86400) / 3600 ))
MINUTES=$(( (TOTAL_TIME % 3600) / 60 ))
SECONDS=$((TOTAL_TIME % 60))

# Display the total runtime in days, hours, minutes, and seconds
echo "Total execution time: ${DAYS} days, ${HOURS} hours, ${MINUTES} minutes, and ${SECONDS} seconds"

